// Mocks generated by Mockito 5.4.4 from annotations
// in happ_eats/test/controllers/diet_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:file_picker/file_picker.dart' as _i10;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:happ_eats/models/application.dart' as _i7;
import 'package:happ_eats/models/diet.dart' as _i13;
import 'package:happ_eats/models/message.dart' as _i12;
import 'package:happ_eats/models/user.dart' as _i6;
import 'package:happ_eats/services/auth_service.dart' as _i4;
import 'package:happ_eats/services/file_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseStorage_2 extends _i1.SmartFake
    implements _i3.FirebaseStorage {
  _FakeFirebaseStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthService_3 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_4 extends _i1.SmartFake
    implements _i5.FirebaseFirestore {
  _FakeFirebaseFirestore_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_5 extends _i1.SmartFake implements _i5.WriteBatch {
  _FakeWriteBatch_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_6 extends _i1.SmartFake implements _i6.UserModel {
  _FakeUserModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApplicationModel_7 extends _i1.SmartFake
    implements _i7.ApplicationModel {
  _FakeApplicationModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_8<T extends Object?> extends _i1.SmartFake
    implements _i5.QuerySnapshot<T> {
  _FakeQuerySnapshot_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);

  @override
  _i8.Stream<_i2.User?> authStateChangesStream() => (super.noSuchMethod(
        Invocation.method(
          #authStateChangesStream,
          [],
        ),
        returnValue: _i8.Stream<_i2.User?>.empty(),
        returnValueForMissingStub: _i8.Stream<_i2.User?>.empty(),
      ) as _i8.Stream<_i2.User?>);

  @override
  _i8.Future<_i2.UserCredential> createUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i2.UserCredential>);

  @override
  _i8.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateUserEmail,
          [newEmail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserPassword(String? newPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [newPassword],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.UserCredential> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i2.UserCredential>);

  @override
  _i8.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i9.FileService {
  @override
  _i3.FirebaseStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.FirebaseStorage);

  @override
  _i4.AuthService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i4.AuthService);

  @override
  _i8.Future<_i10.FilePickerResult?> getImageFile() => (super.noSuchMethod(
        Invocation.method(
          #getImageFile,
          [],
        ),
        returnValue: _i8.Future<_i10.FilePickerResult?>.value(),
        returnValueForMissingStub: _i8.Future<_i10.FilePickerResult?>.value(),
      ) as _i8.Future<_i10.FilePickerResult?>);

  @override
  _i8.Future<_i10.FilePickerResult?> getDietFile() => (super.noSuchMethod(
        Invocation.method(
          #getDietFile,
          [],
        ),
        returnValue: _i8.Future<_i10.FilePickerResult?>.value(),
        returnValueForMissingStub: _i8.Future<_i10.FilePickerResult?>.value(),
      ) as _i8.Future<_i10.FilePickerResult?>);

  @override
  String generateRandomString(int? len) => (super.noSuchMethod(
        Invocation.method(
          #generateRandomString,
          [len],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateRandomString,
            [len],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #generateRandomString,
            [len],
          ),
        ),
      ) as String);

  @override
  _i8.Future<String> uploadImageFile(
    _i10.FilePickerResult? file,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageFile,
          [
            file,
            name,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageFile,
            [
              file,
              name,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageFile,
            [
              file,
              name,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String?> downloadDietFile(
    String? fileName,
    String? professional,
    String? patient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDietFile,
          [
            fileName,
            professional,
            patient,
          ],
        ),
        returnValue: _i8.Future<String?>.value(),
        returnValueForMissingStub: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String?> uploadDietFile(
    _i10.FilePickerResult? file,
    String? patient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDietFile,
          [
            file,
            patient,
          ],
        ),
        returnValue: _i8.Future<String?>.value(),
        returnValueForMissingStub: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String?> deleteFile(
    String? fileName,
    String? userPatient,
    String? userProfessional,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [
            fileName,
            userPatient,
            userProfessional,
          ],
        ),
        returnValue: _i8.Future<String?>.value(),
        returnValueForMissingStub: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String?> deleteImage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [url],
        ),
        returnValue: _i8.Future<String?>.value(),
        returnValueForMissingStub: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i8.Future<_i5.WriteBatch> createUser(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
    String? newLastName,
    String? newTel,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            batch,
            uid,
            newFirstName,
            newLastName,
            newTel,
            newGender,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createUser,
            [
              batch,
              uid,
              newFirstName,
              newLastName,
              newTel,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createUser,
            [
              batch,
              uid,
              newFirstName,
              newLastName,
              newTel,
              newGender,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> deleteUser(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteUser,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteUser,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateUserTel(
    _i5.WriteBatch? batch,
    String? uid,
    String? newTel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserTel,
          [
            batch,
            uid,
            newTel,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserTel,
            [
              batch,
              uid,
              newTel,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserTel,
            [
              batch,
              uid,
              newTel,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateUserFirstName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserFirstName,
          [
            batch,
            uid,
            newFirstName,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateUserLastName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newLastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLastName,
          [
            batch,
            uid,
            newLastName,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateUserGender(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGender,
          [
            batch,
            uid,
            newGender,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i6.UserModel> getUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [uid],
        ),
        returnValue: _i8.Future<_i6.UserModel>.value(_FakeUserModel_6(
          this,
          Invocation.method(
            #getUser,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.UserModel>.value(_FakeUserModel_6(
          this,
          Invocation.method(
            #getUser,
            [uid],
          ),
        )),
      ) as _i8.Future<_i6.UserModel>);

  @override
  _i8.Future<_i5.WriteBatch> addDishes(
    _i5.WriteBatch? batch,
    String? id,
    String? user,
    String? dishName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDishes,
          [
            batch,
            id,
            user,
            dishName,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addDishes,
            [
              batch,
              id,
              user,
              dishName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addDishes,
            [
              batch,
              id,
              user,
              dishName,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> removeDishes(
    _i5.WriteBatch? batch,
    String? id,
    String? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDishes,
          [
            batch,
            id,
            user,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #removeDishes,
            [
              batch,
              id,
              user,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #removeDishes,
            [
              batch,
              id,
              user,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i12.MessageRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i8.Stream<_i5.QuerySnapshot<Object?>?> getMessagesForAmount(
    int? amount,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForAmount,
          [
            amount,
            uid,
          ],
        ),
        returnValue: _i8.Stream<_i5.QuerySnapshot<Object?>?>.empty(),
        returnValueForMissingStub:
            _i8.Stream<_i5.QuerySnapshot<Object?>?>.empty(),
      ) as _i8.Stream<_i5.QuerySnapshot<Object?>?>);

  @override
  _i8.Future<_i5.WriteBatch> sendMessage(
    _i5.WriteBatch? batch,
    String? uid,
    String? toID,
    String? fromID,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            batch,
            uid,
            toID,
            fromID,
            text,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #sendMessage,
            [
              batch,
              uid,
              toID,
              fromID,
              text,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #sendMessage,
            [
              batch,
              uid,
              toID,
              fromID,
              text,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> deleteAllUserMessages(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserMessages,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMessages,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMessages,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);
}

/// A class which mocks [ApplicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationRepository extends _i1.Mock
    implements _i7.ApplicationRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i8.Future<Map<String, dynamic>> getApplicationForUserState(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationForUserState,
          [uid],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Stream<_i5.QuerySnapshot<Object?>> getAllApplicationsByType(
    String? type,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllApplicationsByType,
          [
            type,
            amount,
          ],
        ),
        returnValue: _i8.Stream<_i5.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i8.Stream<_i5.QuerySnapshot<Object?>>.empty(),
      ) as _i8.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i8.Future<_i5.WriteBatch> createApplication(
    _i5.WriteBatch? batch,
    String? newUser,
    String? newFirstName,
    String? newLastName,
    String? newGender,
    String? newMedicalCondition,
    double? newWeight,
    double? newHeight,
    DateTime? newBirthday,
    String? newObjectives,
    String? newType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApplication,
          [
            batch,
            newUser,
            newFirstName,
            newLastName,
            newGender,
            newMedicalCondition,
            newWeight,
            newHeight,
            newBirthday,
            newObjectives,
            newType,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createApplication,
            [
              batch,
              newUser,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createApplication,
            [
              batch,
              newUser,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i7.ApplicationModel> getApplicationForUser(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationForUser,
          [uid],
        ),
        returnValue:
            _i8.Future<_i7.ApplicationModel>.value(_FakeApplicationModel_7(
          this,
          Invocation.method(
            #getApplicationForUser,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i7.ApplicationModel>.value(_FakeApplicationModel_7(
          this,
          Invocation.method(
            #getApplicationForUser,
            [uid],
          ),
        )),
      ) as _i8.Future<_i7.ApplicationModel>);

  @override
  _i8.Future<_i5.WriteBatch> assignApplication(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignApplication,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #assignApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #assignApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> deleteApplication(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApplication,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);
}

/// A class which mocks [DietRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietRepository extends _i1.Mock implements _i13.DietRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i8.Future<_i5.WriteBatch> createDiet(
    _i5.WriteBatch? batch,
    String? newPatient,
    String? newProfessional,
    String? newFirstName,
    dynamic newLastName,
    String? newGender,
    String? newMedicalCondition,
    double? newWeight,
    double? newHeight,
    DateTime? newBirthday,
    String? newObjectives,
    String? newType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDiet,
          [
            batch,
            newPatient,
            newProfessional,
            newFirstName,
            newLastName,
            newGender,
            newMedicalCondition,
            newWeight,
            newHeight,
            newBirthday,
            newObjectives,
            newType,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDiet,
            [
              batch,
              newPatient,
              newProfessional,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDiet,
            [
              batch,
              newPatient,
              newProfessional,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietFirstName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietFirstName,
          [
            batch,
            uid,
            newFirstName,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietLastName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newLastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietLastName,
          [
            batch,
            uid,
            newLastName,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietGender(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietGender,
          [
            batch,
            uid,
            newGender,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietMedicalCondition(
    _i5.WriteBatch? batch,
    String? uid,
    String? newMedicalCondition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietMedicalCondition,
          [
            batch,
            uid,
            newMedicalCondition,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietWeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newWeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietWeight,
          [
            batch,
            uid,
            newWeight,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietHeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietHeight,
          [
            batch,
            uid,
            newHeight,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> updateDietBirthday(
    _i5.WriteBatch? batch,
    String? uid,
    String? newBirthday,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietBirthday,
          [
            batch,
            uid,
            newBirthday,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> deleteDiet(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDiet,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDiet,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDiet,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Future<_i5.WriteBatch> addRefApplication(
    _i5.WriteBatch? batch,
    String? uid,
    String? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRefApplication,
          [
            batch,
            uid,
            url,
          ],
        ),
        returnValue: _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addRefApplication,
            [
              batch,
              uid,
              url,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addRefApplication,
            [
              batch,
              uid,
              url,
            ],
          ),
        )),
      ) as _i8.Future<_i5.WriteBatch>);

  @override
  _i8.Stream<_i5.QuerySnapshot<Map<String, dynamic>>> getAllDiets(
    String? type,
    int? amount,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDiets,
          [
            type,
            amount,
            id,
          ],
        ),
        returnValue:
            _i8.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i8.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i8.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> getDietForUser(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDietForUser,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i5.QuerySnapshot<Map<String, dynamic>>>
      getAllDietsForProfessional(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getAllDietsForProfessional,
              [id],
            ),
            returnValue:
                _i8.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                    _FakeQuerySnapshot_8<Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAllDietsForProfessional,
                [id],
              ),
            )),
            returnValueForMissingStub:
                _i8.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                    _FakeQuerySnapshot_8<Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAllDietsForProfessional,
                [id],
              ),
            )),
          ) as _i8.Future<_i5.QuerySnapshot<Map<String, dynamic>>>);
}
