// Mocks generated by Mockito 5.4.4 from annotations
// in happ_eats/test/controllers/user_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:file_picker/file_picker.dart' as _i12;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:happ_eats/models/application.dart' as _i9;
import 'package:happ_eats/models/appointed_meal.dart' as _i16;
import 'package:happ_eats/models/diet.dart' as _i17;
import 'package:happ_eats/models/dish.dart' as _i15;
import 'package:happ_eats/models/message.dart' as _i14;
import 'package:happ_eats/models/patient.dart' as _i7;
import 'package:happ_eats/models/professional.dart' as _i8;
import 'package:happ_eats/models/user.dart' as _i6;
import 'package:happ_eats/services/auth_service.dart' as _i4;
import 'package:happ_eats/services/file_service.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseStorage_2 extends _i1.SmartFake
    implements _i3.FirebaseStorage {
  _FakeFirebaseStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthService_3 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_4 extends _i1.SmartFake
    implements _i5.FirebaseFirestore {
  _FakeFirebaseFirestore_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteBatch_5 extends _i1.SmartFake implements _i5.WriteBatch {
  _FakeWriteBatch_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_6 extends _i1.SmartFake implements _i6.UserModel {
  _FakeUserModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePatientModel_7 extends _i1.SmartFake implements _i7.PatientModel {
  _FakePatientModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfessionalModel_8 extends _i1.SmartFake
    implements _i8.ProfessionalModel {
  _FakeProfessionalModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_9<T extends Object?> extends _i1.SmartFake
    implements _i5.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuerySnapshot_10<T extends Object?> extends _i1.SmartFake
    implements _i5.QuerySnapshot<T> {
  _FakeQuerySnapshot_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApplicationModel_11 extends _i1.SmartFake
    implements _i9.ApplicationModel {
  _FakeApplicationModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i2.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeFirebaseAuth_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.FirebaseAuth);

  @override
  _i10.Stream<_i2.User?> authStateChangesStream() => (super.noSuchMethod(
        Invocation.method(
          #authStateChangesStream,
          [],
        ),
        returnValue: _i10.Stream<_i2.User?>.empty(),
        returnValueForMissingStub: _i10.Stream<_i2.User?>.empty(),
      ) as _i10.Stream<_i2.User?>);

  @override
  _i10.Future<_i2.UserCredential> createUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i10.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #createUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i10.Future<_i2.UserCredential>);

  @override
  _i10.Future<void> deleteUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [uid],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateUserEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateUserEmail,
          [newEmail],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateUserPassword(String? newPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [newPassword],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i2.UserCredential> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i10.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i2.UserCredential>.value(_FakeUserCredential_1(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i10.Future<_i2.UserCredential>);

  @override
  _i10.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i11.FileService {
  @override
  _i3.FirebaseStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.FirebaseStorage);

  @override
  _i4.AuthService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i4.AuthService);

  @override
  _i10.Future<_i12.FilePickerResult?> getImageFile() => (super.noSuchMethod(
        Invocation.method(
          #getImageFile,
          [],
        ),
        returnValue: _i10.Future<_i12.FilePickerResult?>.value(),
        returnValueForMissingStub: _i10.Future<_i12.FilePickerResult?>.value(),
      ) as _i10.Future<_i12.FilePickerResult?>);

  @override
  _i10.Future<_i12.FilePickerResult?> getDietFile() => (super.noSuchMethod(
        Invocation.method(
          #getDietFile,
          [],
        ),
        returnValue: _i10.Future<_i12.FilePickerResult?>.value(),
        returnValueForMissingStub: _i10.Future<_i12.FilePickerResult?>.value(),
      ) as _i10.Future<_i12.FilePickerResult?>);

  @override
  String generateRandomString(int? len) => (super.noSuchMethod(
        Invocation.method(
          #generateRandomString,
          [len],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #generateRandomString,
            [len],
          ),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #generateRandomString,
            [len],
          ),
        ),
      ) as String);

  @override
  _i10.Future<String> uploadImageFile(
    _i12.FilePickerResult? file,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageFile,
          [
            file,
            name,
          ],
        ),
        returnValue: _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageFile,
            [
              file,
              name,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageFile,
            [
              file,
              name,
            ],
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<String?> downloadDietFile(
    String? fileName,
    String? professional,
    String? patient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadDietFile,
          [
            fileName,
            professional,
            patient,
          ],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<String?> uploadDietFile(
    _i12.FilePickerResult? file,
    String? patient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDietFile,
          [
            file,
            patient,
          ],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<String?> deleteFile(
    String? fileName,
    String? userPatient,
    String? userProfessional,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [
            fileName,
            userPatient,
            userProfessional,
          ],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);

  @override
  _i10.Future<String?> deleteImage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [url],
        ),
        returnValue: _i10.Future<String?>.value(),
        returnValueForMissingStub: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createUser(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
    String? newLastName,
    String? newTel,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            batch,
            uid,
            newFirstName,
            newLastName,
            newTel,
            newGender,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createUser,
            [
              batch,
              uid,
              newFirstName,
              newLastName,
              newTel,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createUser,
            [
              batch,
              uid,
              newFirstName,
              newLastName,
              newTel,
              newGender,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteUser(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteUser,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteUser,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateUserTel(
    _i5.WriteBatch? batch,
    String? uid,
    String? newTel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserTel,
          [
            batch,
            uid,
            newTel,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserTel,
            [
              batch,
              uid,
              newTel,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserTel,
            [
              batch,
              uid,
              newTel,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateUserFirstName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserFirstName,
          [
            batch,
            uid,
            newFirstName,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateUserLastName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newLastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLastName,
          [
            batch,
            uid,
            newLastName,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateUserGender(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGender,
          [
            batch,
            uid,
            newGender,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateUserGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i6.UserModel> getUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [uid],
        ),
        returnValue: _i10.Future<_i6.UserModel>.value(_FakeUserModel_6(
          this,
          Invocation.method(
            #getUser,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i6.UserModel>.value(_FakeUserModel_6(
          this,
          Invocation.method(
            #getUser,
            [uid],
          ),
        )),
      ) as _i10.Future<_i6.UserModel>);

  @override
  _i10.Future<_i5.WriteBatch> addDishes(
    _i5.WriteBatch? batch,
    String? id,
    String? user,
    String? dishName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDishes,
          [
            batch,
            id,
            user,
            dishName,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addDishes,
            [
              batch,
              id,
              user,
              dishName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addDishes,
            [
              batch,
              id,
              user,
              dishName,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> removeDishes(
    _i5.WriteBatch? batch,
    String? id,
    String? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeDishes,
          [
            batch,
            id,
            user,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #removeDishes,
            [
              batch,
              id,
              user,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #removeDishes,
            [
              batch,
              id,
              user,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);
}

/// A class which mocks [PatientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientRepository extends _i1.Mock implements _i7.PatientRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createPatient(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
    String? newMedicalCondition,
    String? newWeight,
    String? newHeight,
    String? newBirthday,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPatient,
          [
            batch,
            uid,
            newGender,
            newMedicalCondition,
            newWeight,
            newHeight,
            newBirthday,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createPatient,
            [
              batch,
              uid,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createPatient,
            [
              batch,
              uid,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deletePatient(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePatient,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deletePatient,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deletePatient,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updatePatientGender(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePatientGender,
          [
            batch,
            uid,
            newGender,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updatePatientMedicalCondition(
    _i5.WriteBatch? batch,
    String? uid,
    String? newMedicalCondition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePatientMedicalCondition,
          [
            batch,
            uid,
            newMedicalCondition,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updatePatientWeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newWeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePatientWeight,
          [
            batch,
            uid,
            newWeight,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updatePatientHeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePatientHeight,
          [
            batch,
            uid,
            newHeight,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updatePatientBirthday(
    _i5.WriteBatch? batch,
    String? uid,
    String? newBirthday,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePatientBirthday,
          [
            batch,
            uid,
            newBirthday,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updatePatientBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<bool> isPatient(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #isPatient,
          [uid],
        ),
        returnValue: _i10.Future<bool>.value(false),
        returnValueForMissingStub: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i7.PatientModel> getPatient(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getPatient,
          [uid],
        ),
        returnValue: _i10.Future<_i7.PatientModel>.value(_FakePatientModel_7(
          this,
          Invocation.method(
            #getPatient,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i7.PatientModel>.value(_FakePatientModel_7(
          this,
          Invocation.method(
            #getPatient,
            [uid],
          ),
        )),
      ) as _i10.Future<_i7.PatientModel>);
}

/// A class which mocks [ProfessionalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfessionalRepository extends _i1.Mock
    implements _i8.ProfessionalRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createProfessional(
    _i5.WriteBatch? batch,
    String? uid,
    String? newCollegeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfessional,
          [
            batch,
            uid,
            newCollegeNumber,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createProfessional,
            [
              batch,
              uid,
              newCollegeNumber,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createProfessional,
            [
              batch,
              uid,
              newCollegeNumber,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteProfessional(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProfessional,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteProfessional,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteProfessional,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i8.ProfessionalModel> getProfessional(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfessional,
          [uid],
        ),
        returnValue:
            _i10.Future<_i8.ProfessionalModel>.value(_FakeProfessionalModel_8(
          this,
          Invocation.method(
            #getProfessional,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i8.ProfessionalModel>.value(_FakeProfessionalModel_8(
          this,
          Invocation.method(
            #getProfessional,
            [uid],
          ),
        )),
      ) as _i10.Future<_i8.ProfessionalModel>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i14.MessageRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Stream<_i5.QuerySnapshot<Object?>?> getMessagesForAmount(
    int? amount,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesForAmount,
          [
            amount,
            uid,
          ],
        ),
        returnValue: _i10.Stream<_i5.QuerySnapshot<Object?>?>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Object?>?>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Object?>?>);

  @override
  _i10.Future<_i5.WriteBatch> sendMessage(
    _i5.WriteBatch? batch,
    String? uid,
    String? toID,
    String? fromID,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            batch,
            uid,
            toID,
            fromID,
            text,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #sendMessage,
            [
              batch,
              uid,
              toID,
              fromID,
              text,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #sendMessage,
            [
              batch,
              uid,
              toID,
              fromID,
              text,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteAllUserMessages(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserMessages,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMessages,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMessages,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);
}

/// A class which mocks [DishRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDishRepository extends _i1.Mock implements _i15.DishRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createDish(
    _i5.WriteBatch? batch,
    String? id,
    String? user,
    String? dishName,
    String? description,
    Map<String, dynamic>? nutritionalInfo,
    String? imageName,
    Map<String, dynamic>? ingredientes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDish,
          [
            batch,
            id,
            user,
            dishName,
            description,
            nutritionalInfo,
            imageName,
            ingredientes,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDish,
            [
              batch,
              id,
              user,
              dishName,
              description,
              nutritionalInfo,
              imageName,
              ingredientes,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDish,
            [
              batch,
              id,
              user,
              dishName,
              description,
              nutritionalInfo,
              imageName,
              ingredientes,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteDish(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDish,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDish,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDish,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>> getAllDishes(
    int? amount,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDishes,
          [
            amount,
            id,
          ],
        ),
        returnValue:
            _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i10.Future<_i5.DocumentSnapshot<Map<String, dynamic>>> getDish(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDish,
          [id],
        ),
        returnValue:
            _i10.Future<_i5.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_9<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDish,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_9<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDish,
            [id],
          ),
        )),
      ) as _i10.Future<_i5.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>> getAllDishesFuture(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDishesFuture,
          [id],
        ),
        returnValue: _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
            _FakeQuerySnapshot_10<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getAllDishesFuture,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                _FakeQuerySnapshot_10<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getAllDishesFuture,
            [id],
          ),
        )),
      ) as _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>);
}

/// A class which mocks [AppointedMealRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointedMealRepository extends _i1.Mock
    implements _i16.AppointedMealRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createAppointedMeal(
    _i5.WriteBatch? batch,
    String? id,
    String? diet,
    String? professional,
    String? patient,
    DateTime? appointedDate,
    String? dish,
    String? dishName,
    int? mealOrder,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAppointedMeal,
          [
            batch,
            id,
            diet,
            professional,
            patient,
            appointedDate,
            dish,
            dishName,
            mealOrder,
            values,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createAppointedMeal,
            [
              batch,
              id,
              diet,
              professional,
              patient,
              appointedDate,
              dish,
              dishName,
              mealOrder,
              values,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createAppointedMeal,
            [
              batch,
              id,
              diet,
              professional,
              patient,
              appointedDate,
              dish,
              dishName,
              mealOrder,
              values,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> signalIssuesAppointedMeal(
    _i5.WriteBatch? batch,
    String? id,
    String? note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signalIssuesAppointedMeal,
          [
            batch,
            id,
            note,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #signalIssuesAppointedMeal,
            [
              batch,
              id,
              note,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #signalIssuesAppointedMeal,
            [
              batch,
              id,
              note,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> consumedCorrectlyAppointedMeal(
    _i5.WriteBatch? batch,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #consumedCorrectlyAppointedMeal,
          [
            batch,
            id,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #consumedCorrectlyAppointedMeal,
            [
              batch,
              id,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #consumedCorrectlyAppointedMeal,
            [
              batch,
              id,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Stream<_i5.QuerySnapshot<Object?>> getAllAppointmentsForToday(
    DateTime? date,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAppointmentsForToday,
          [
            date,
            id,
          ],
        ),
        returnValue: _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i10.Stream<_i5.QuerySnapshot<Object?>> getAllAppointmentsStream(
    DateTime? dateStart,
    DateTime? dateEnd,
    String? idPatient,
    dynamic idProfessional,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAppointmentsStream,
          [
            dateStart,
            dateEnd,
            idPatient,
            idProfessional,
          ],
        ),
        returnValue: _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i10.Future<_i5.WriteBatch> deleteAllUserMeals(
    _i5.WriteBatch? batch,
    String? id,
    bool? isPatient,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserMeals,
          [
            batch,
            id,
            isPatient,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMeals,
            [
              batch,
              id,
              isPatient,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteAllUserMeals,
            [
              batch,
              id,
              isPatient,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);
}

/// A class which mocks [ApplicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApplicationRepository extends _i1.Mock
    implements _i9.ApplicationRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<Map<String, dynamic>> getApplicationForUserState(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationForUserState,
          [uid],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Stream<_i5.QuerySnapshot<Object?>> getAllApplicationsByType(
    String? type,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllApplicationsByType,
          [
            type,
            amount,
          ],
        ),
        returnValue: _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Object?>>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i10.Future<_i5.WriteBatch> createApplication(
    _i5.WriteBatch? batch,
    String? newUser,
    String? newFirstName,
    String? newLastName,
    String? newGender,
    String? newMedicalCondition,
    double? newWeight,
    double? newHeight,
    DateTime? newBirthday,
    String? newObjectives,
    String? newType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createApplication,
          [
            batch,
            newUser,
            newFirstName,
            newLastName,
            newGender,
            newMedicalCondition,
            newWeight,
            newHeight,
            newBirthday,
            newObjectives,
            newType,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createApplication,
            [
              batch,
              newUser,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createApplication,
            [
              batch,
              newUser,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i9.ApplicationModel> getApplicationForUser(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationForUser,
          [uid],
        ),
        returnValue:
            _i10.Future<_i9.ApplicationModel>.value(_FakeApplicationModel_11(
          this,
          Invocation.method(
            #getApplicationForUser,
            [uid],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i9.ApplicationModel>.value(_FakeApplicationModel_11(
          this,
          Invocation.method(
            #getApplicationForUser,
            [uid],
          ),
        )),
      ) as _i10.Future<_i9.ApplicationModel>);

  @override
  _i10.Future<_i5.WriteBatch> assignApplication(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignApplication,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #assignApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #assignApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteApplication(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApplication,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteApplication,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);
}

/// A class which mocks [DietRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDietRepository extends _i1.Mock implements _i17.DietRepository {
  @override
  _i5.FirebaseFirestore get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_4(
          this,
          Invocation.getter(#db),
        ),
      ) as _i5.FirebaseFirestore);

  @override
  _i10.Future<_i5.WriteBatch> createDiet(
    _i5.WriteBatch? batch,
    String? newPatient,
    String? newProfessional,
    String? newFirstName,
    dynamic newLastName,
    String? newGender,
    String? newMedicalCondition,
    double? newWeight,
    double? newHeight,
    DateTime? newBirthday,
    String? newObjectives,
    String? newType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDiet,
          [
            batch,
            newPatient,
            newProfessional,
            newFirstName,
            newLastName,
            newGender,
            newMedicalCondition,
            newWeight,
            newHeight,
            newBirthday,
            newObjectives,
            newType,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDiet,
            [
              batch,
              newPatient,
              newProfessional,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #createDiet,
            [
              batch,
              newPatient,
              newProfessional,
              newFirstName,
              newLastName,
              newGender,
              newMedicalCondition,
              newWeight,
              newHeight,
              newBirthday,
              newObjectives,
              newType,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietFirstName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newFirstName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietFirstName,
          [
            batch,
            uid,
            newFirstName,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietFirstName,
            [
              batch,
              uid,
              newFirstName,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietLastName(
    _i5.WriteBatch? batch,
    String? uid,
    String? newLastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietLastName,
          [
            batch,
            uid,
            newLastName,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietLastName,
            [
              batch,
              uid,
              newLastName,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietGender(
    _i5.WriteBatch? batch,
    String? uid,
    String? newGender,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietGender,
          [
            batch,
            uid,
            newGender,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietGender,
            [
              batch,
              uid,
              newGender,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietMedicalCondition(
    _i5.WriteBatch? batch,
    String? uid,
    String? newMedicalCondition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietMedicalCondition,
          [
            batch,
            uid,
            newMedicalCondition,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietMedicalCondition,
            [
              batch,
              uid,
              newMedicalCondition,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietWeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newWeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietWeight,
          [
            batch,
            uid,
            newWeight,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietWeight,
            [
              batch,
              uid,
              newWeight,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietHeight(
    _i5.WriteBatch? batch,
    String? uid,
    String? newHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietHeight,
          [
            batch,
            uid,
            newHeight,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietHeight,
            [
              batch,
              uid,
              newHeight,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> updateDietBirthday(
    _i5.WriteBatch? batch,
    String? uid,
    String? newBirthday,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDietBirthday,
          [
            batch,
            uid,
            newBirthday,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #updateDietBirthday,
            [
              batch,
              uid,
              newBirthday,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> deleteDiet(
    _i5.WriteBatch? batch,
    String? uid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDiet,
          [
            batch,
            uid,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDiet,
            [
              batch,
              uid,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #deleteDiet,
            [
              batch,
              uid,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Future<_i5.WriteBatch> addRefApplication(
    _i5.WriteBatch? batch,
    String? uid,
    String? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRefApplication,
          [
            batch,
            uid,
            url,
          ],
        ),
        returnValue: _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addRefApplication,
            [
              batch,
              uid,
              url,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i10.Future<_i5.WriteBatch>.value(_FakeWriteBatch_5(
          this,
          Invocation.method(
            #addRefApplication,
            [
              batch,
              uid,
              url,
            ],
          ),
        )),
      ) as _i10.Future<_i5.WriteBatch>);

  @override
  _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>> getAllDiets(
    String? type,
    int? amount,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDiets,
          [
            type,
            amount,
            id,
          ],
        ),
        returnValue:
            _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
        returnValueForMissingStub:
            _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i10.Stream<_i5.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> getDietForUser(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDietForUser,
          [id],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>
      getAllDietsForProfessional(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getAllDietsForProfessional,
              [id],
            ),
            returnValue:
                _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                    _FakeQuerySnapshot_10<Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAllDietsForProfessional,
                [id],
              ),
            )),
            returnValueForMissingStub:
                _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                    _FakeQuerySnapshot_10<Map<String, dynamic>>(
              this,
              Invocation.method(
                #getAllDietsForProfessional,
                [id],
              ),
            )),
          ) as _i10.Future<_i5.QuerySnapshot<Map<String, dynamic>>>);
}
